FROM actency/docker-solr:3.6

ADD https://raw.githubusercontent.com/composer/packagist/master/doc/schema.xml /opt/solr/example/solr/conf/schema.xml
ADD https://raw.githubusercontent.com/composer/packagist/master/doc/solrconfig.xml /opt/solr/example/solr/conf/solrconfig.xml